### PR TITLE
Node write optimization and bug fixes

### PR DESCRIPTION
**Pull request by nithinj**
* Node write is optimized based on MODIFY flag
* Node state was showing BUSY after a restart

### CODE REVIEW

**Comment by suresh-thelkar** [comment]
@nithinj, It looks many test cases are failing in all platforms. Can you please take a look ?
Also the PR includes the changes of my PR i.e. https://github.com/subhasisb/pbspro/pull/56. You can remove these changes. It would be easy for people reviewing this PR.  Add a note here saying that this PR needs to be merged only after PR #56. 

However for our testing case we can have PR #56 changes as well in another private branch of yours.

**Comment by nithinj** [comment]
> @nithinj, It looks like many test cases are failing in all platforms. Can you please take a look ?
> Also the PR includes the changes of my PR i.e. #56. You can remove these changes. It would be easy for people reviewing this PR. Add a note here saying that this PR needs to be merged only after PR #56.
> 
> However for our testing case we can have PR #56 changes as well in another private branch of yours.

done!
I've pushed the changes in a hurry in case if you want to take a look at the server to mom connection issues. Server is doing an rpp_open to alien mom and sending job using PBSD_Queuejop(), where as mom logs displays "premature end of message" and COMM discards the connection. I'll take a closer look at this.

**Comment by nithinj** [comment]
@subhasisb ,
End to end job-cycle with multi-server for basic run works now. Can you review and merge in the changes so that we can do more testing with more jobs/moms?

**Comment by suresh-thelkar** [comment]
@subhasisb, The current PR has dependency with the PR #56 and PR #57. Please merge all of these three PRs together.

**Pull request merged**
