### PR TITLE
reduce and optimize queue object loads

### PR DESCRIPTION
**Pull request by Shrini-h**
#### Describe Bug or Feature

Due to https://github.com/subhasisb/pbspro/pull/3/commits/ff933502d5bf9d99ac3596b0ab3246ebf2c51ab5 the queue object was loaded in every place where `ji_qhdr` was accessed, which resulted in frequent `select_que` statements to db.

#### Describe Your Change

reintroduced `ji_qhdr` member of job object to point to recently loaded queue object cache. Also added queue load operations using `find_queuebyname()` at only necessary places. The resulting postgresql log with `log_statement=all` is attached here.

#### Attach Test and Valgrind Logs/Output

[postgresql-Mon.log](https://github.com/subhasisb/pbspro/files/3392676/postgresql-Mon.log)

### CODE REVIEW

**Comment by Shrini-h** [comment]
> Please check the previous commit from myself, probably this change is not required any more.
> Besides, i do not see any locking in this code. Did you miss it?

Actually as mentioned in description I was focusing on reverting https://github.com/subhasisb/pbspro/commit/ff933502d5bf9d99ac3596b0ab3246ebf2c51ab5 to reduce queue loads which you pointed out in the pgsql logs. so did not check on locking stuff
Since git did not show conflict and neither there was compiler/runtime errors I did not bother to check the recent commits. Ok will now study your recent commits, thanks

**Comment by subhasisb** [comment]
> > Please check the previous commit from myself, probably this change is not required any more.
> > Besides, i do not see any locking in this code. Did you miss it?
> 
> Actually as mentioned in description I was focusing on reverting [ff93350](https://github.com/subhasisb/pbspro/commit/ff933502d5bf9d99ac3596b0ab3246ebf2c51ab5) to reduce queue loads which you pointed out in the pgsql logs. so did not check on locking stuff
> Since git did not show conflict and neither there was compiler/runtime errors I did not bother to check the recent commits. Ok will now study your recent commits, thanks

But we need to lock when required for consistency

**Comment by Shrini-h** [comment]
> > > Please check the previous commit from myself, probably this change is not required any more.
> > > Besides, i do not see any locking in this code. Did you miss it?
> > 
> > 
> > Actually as mentioned in description I was focusing on reverting [ff93350](https://github.com/subhasisb/pbspro/commit/ff933502d5bf9d99ac3596b0ab3246ebf2c51ab5) to reduce queue loads which you pointed out in the pgsql logs. so did not check on locking stuff
> > Since git did not show conflict and neither there was compiler/runtime errors I did not bother to check the recent commits. Ok will now study your recent commits, thanks
> 
> But we need to lock when required for consistency

Yes I agree, Was thinking of working for it in a different PR after discussions or syncup

**Comment by subhasisb** [comment]
okies, thanks

**Pull request closed without merging**
