### PR TITLE
Added work task to delete objects from db and fixed some bugs

### PR DESCRIPTION
**Pull request by Bhagat-Rajput**
#### Describe Your Change

1. Server flag attribute was commented earlier due to value discrepancy during load from db is fixed now.
2. Added a timed task to delete all the queues(normal or resv) from the db and task will run after every 30 min as of now (we can change it later as per the requirements)
3. Fixed a bug in get_all_db_queues() in which if last que is marked as deleted in db then every time it was fetching all the queues instead of delta records.
4. Added a time interval of 30 secs in pbsd_main during get_all_db_queues() call.

#### Attach Test and Valgrind Logs/Output

[ptl_smoketest.txt](https://github.com/subhasisb/pbspro/files/3742364/ptl_smoketest.txt)

### CODE REVIEW

**Comment by Bhagat-Rajput** [comment]
Hello @subhasisb, i have addressed your comment. Please review it.
Hey @nithinj, added node deletion part to the timed task as well so please have a look at it.

**Comment by Bhagat-Rajput** [comment]
Travis is throwing error because "**nd_deleted**" column has not been added yet and it will be added by @nithinj PR. So will merge this PR after nithin's PR. Thanks!

**Comment by nithinj** [comment]
Oops! I'm waiting on https://github.com/subhasisb/pbspro/pull/48 to get merged to raise the node deletion one, because of lot many dependencies.

**Comment by subhasisb** [comment]
@Bhagat-Rajput can you please resolve conflicts and submit this again?

**Comment by nithinj** [comment]
node deletion PR: https://github.com/subhasisb/pbspro/pull/49

**Comment by subhasisb** [comment]
Can you check and resolve this?

**Comment by Bhagat-Rajput** [comment]
This PR is directly depenedent on @nithinj 's PR [#49](https://github.com/subhasisb/pbspro/pull/49), I will resolve all the conflicts once that PR will be merged to multi_server_branch. Thanks!

**Comment by Bhagat-Rajput** [comment]
@subhasisb, I've resolved all the conflicts and now it's ready to merge. Thanks

**Comment by subhasisb** [comment]
@Bhagat-Rajput once more please

**Pull request merged**
